using PX.CCProcessingBase.Interfaces.V2;
using PX.Common;
using PX.Data.Update.ExchangeService;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.UI;
using static PX.SM.WikiRevision;

namespace AcumaticaDummyCreditCardPlugin
{
    public class ADCPHostedFormProcessor : ICCHostedFormProcessor
    {
        private IEnumerable<SettingsValue> settingValues;

        public ADCPHostedFormProcessor(IEnumerable<SettingsValue> settingValues)
        {
            this.settingValues = settingValues;
        }
        public HostedFormData GetDataForCreateForm(CustomerData customerData, AddressData addressData)
        {
            string baseUrl, hostedFormURL = string.Empty;

            if (HttpContext.Current != null)
            {
                Page currentPage = HttpContext.Current.CurrentHandler as Page;
                if (HttpContext.Current.Request != null && HttpContext.Current.Request.UrlReferrer != null && currentPage != null && HttpContext.Current.Request.Url != null)
                {
                    baseUrl = HttpContext.Current.Request.Url.GetLeftPart(UriPartial.Authority);
                    var baseUrl2 = VirtualPathUtility.ToAbsolute("~/");
                    hostedFormURL = baseUrl + baseUrl2 + "Frames/ADCPPaymentConnector.html";
                }
            }

            string token = GetToken(settingValues);

         

            Dictionary<string, string> parms = new Dictionary<string, string>()
            {
                {"Type", "CreateOnly"},
                {"CPID", customerData.CustomerProfileID},
                {"CustomerCD", customerData.CustomerCD},
                {"Width", "400" },
                {"Height", "300"}
            };

            return new HostedFormData() {
                Caption = "Create Payment Profile",
                Url = hostedFormURL,
                UseGetMethod = true,
                Token = token,
                Parameters = parms
            };
        }

        private string GetToken(IEnumerable<SettingsValue> settingValues)
        { 
            // The token is usually a noonce or similar value that being generated by processing center as an authorization for hosted form to open.
            // To simplify the implementation we will pass the credentials encoded to be used for API requests on hosted form side. This is not to do on live instances.

            List<string> credentials = new List<string>();
            credentials.Add(settingValues.First(x => x.DetailID == ADCPConstants.ADPCURL).Value);
            credentials.Add(settingValues.First(x => x.DetailID == ADCPConstants.ADPCUserName).Value);
            credentials.Add(settingValues.First(x => x.DetailID == ADCPConstants.ADPCPassword).Value);
            credentials.Add(settingValues.First(x => x.DetailID == ADCPConstants.ADPCTenant).Value);
            string creds = string.Join("|", credentials);
            return Convert.ToBase64String(Encoding.UTF8.GetBytes(creds));
        }

        public HostedFormData GetDataForManageForm(CustomerData customerData, CreditCardData cardData)
        {
            throw new System.NotImplementedException();
        }
    }
}